# Generated by Django 2.2.6 on 2020-08-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('tyepName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemUser.SystemUser')),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemUser.UserType')),
            ],
        ),
    ]
