# Generated by Django 2.2.6 on 2020-08-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0002_auto_20200815_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='tyepName',
            new_name='typeName',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='SystemUser.SystemUser'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='SystemUser.UserType'),
        ),
    ]
