# Generated by Django 2.2.6 on 2020-08-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0004_systemuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='userType',
        ),
    ]
