# Generated by Django 2.2.6 on 2020-08-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SystemUser', '0005_remove_systemuser_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('placeTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('placeTypeName', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceLine',
            fields=[
                ('lineId', models.AutoField(primary_key=True, serialize=False)),
                ('lineStatus', models.CharField(choices=[('close', 'close'), ('open', 'open')], default='close', max_length=11)),
                ('user', models.ManyToManyField(blank=True, null=True, to='SystemUser.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInformation',
            fields=[
                ('placeId', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=90)),
                ('placeAddress', models.CharField(max_length=88)),
                ('placeLongitude', models.CharField(max_length=44)),
                ('placeLatitude', models.CharField(max_length=44)),
                ('placeLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.PlaceLine')),
                ('placeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.PlaceType')),
            ],
        ),
    ]
