# Generated by Django 2.2.6 on 2020-08-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinformation',
            name='placeAddress',
            field=models.CharField(max_length=38),
        ),
        migrations.AlterField(
            model_name='placeinformation',
            name='placeLatitude',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='placeinformation',
            name='placeLongitude',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='placeinformation',
            name='placeName',
            field=models.CharField(max_length=30),
        ),
    ]
