# Generated by Django 2.2.6 on 2020-08-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0002_auto_20200817_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeinformation',
            name='placeLine',
        ),
        migrations.RemoveField(
            model_name='placeinformation',
            name='placeType',
        ),
    ]
