# Generated by Django 2.2.6 on 2020-08-16 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0004_auto_20200817_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinformation',
            name='placeLine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.PlaceLine'),
        ),
        migrations.AlterField(
            model_name='placeinformation',
            name='placeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Place.PlaceType'),
        ),
    ]
