# Generated by Django 2.2.6 on 2020-08-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0005_remove_systemuser_usertype'),
        ('Place', '0005_auto_20200817_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinformation',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SystemUser.SystemUser'),
        ),
    ]
