# Generated by Django 2.2.6 on 2020-08-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0005_remove_systemuser_usertype'),
        ('Place', '0006_placeinformation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeline',
            name='user',
        ),
        migrations.CreateModel(
            name='CheckedUser',
            fields=[
                ('checkedId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemUser.SystemUser')),
            ],
        ),
        migrations.AddField(
            model_name='placeline',
            name='checkedUser',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Place.CheckedUser'),
        ),
    ]
