# Generated by Django 2.2.6 on 2020-08-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0009_auto_20200819_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeline',
            name='checkedUser',
        ),
    ]
