# Generated by Django 2.2.6 on 2020-08-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0010_remove_placeline_checkeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeline',
            name='checkedUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Place.CheckedUser'),
            preserve_default=False,
        ),
    ]
