# Generated by Django 2.2.6 on 2020-08-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0011_placeline_checkeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeline',
            name='checkedUser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Place.CheckedUser'),
        ),
    ]
