# Generated by Django 2.2.6 on 2020-08-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0015_auto_20200819_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeline',
            name='checkedUser',
        ),
        migrations.AddField(
            model_name='placeline',
            name='checkedUser',
            field=models.ManyToManyField(blank=True, null=True, to='Place.CheckedUser'),
        ),
    ]
