# Generated by Django 2.2.6 on 2020-09-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0016_auto_20200819_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='placeTypeName',
            field=models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Super Shop', 'Super Shop')], max_length=55),
        ),
    ]
