# Generated by Django 2.2.6 on 2020-09-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0017_auto_20200909_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='placeTypeName',
            field=models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Super Shop', 'Super Shop'), ('Resturant', 'Resturant')], max_length=55),
        ),
    ]
